services:
  sas_robot_driver_kuka:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      TIMEOUT: 20
    command: /bin/bash -c "
      cd /root/sas_robot_driver_kuka_devel/src/sas_robot_driver_kuka/docker
      && chmod +x test.sh
      && ./test.sh"
